language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install flake8"
  - "pip install -r requirements.txt"
before_script: "flake8 . --ignore=E501"
script: "py.test -v -n 10 --driver=Firefox --destructive --sensitiveurl=foo --credentials=credentials.yaml tests"
notifications:
  email: false
